// action - customization reducer
export const SET_MENU = '@customization/SET_MENU';
export const MENU_TOGGLE = '@customization/MENU_TOGGLE';
export const MENU_OPEN = '@customization/MENU_OPEN';
export const SET_FONT_FAMILY = '@customization/SET_FONT_FAMILY';
export const SET_BORDER_RADIUS = '@customization/SET_BORDER_RADIUS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const SET_FILIERES = "SET_FILIERES";
export const SET_FILIERE = "SET_FILIERE";

export const SET_ETUDIANTS = "SET_ETUDIANTS";

export const SET_ACCOUNT_ADDRESS = "SET_ACCOUNT_ADDRESS";
export const SET_WALLET_AUTH_TOKEN = "SET_WALLET_AUTH_TOKEN";

export const GET_PROFILE_STUDENT_SUCCESS = "GET_PROFILE_STUDENT_SUCCESS";
export const GET_PROFILE_STUDENT_FAIL = "GET_PROFILE_STUDENT_FAIL";

export const GET_PRIVATE_PROFILE_STUDENT_SUCCESS = "GET_PRIVATE_PROFILE_STUDENT_SUCCESS";
export const GET_PRIVATE_PROFILE_STUDENT_FAIL = "GET_PRIVATE_PROFILE_STUDENT_FAIL";

export const SET_CERTIFICATS = "SET_CERTIFICATS";